/**
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# Do not edit this file, it will be overwritten
locals {
  project_id             = "cmek-gke-demo"
  project_number         = 234687475375
  project_default_region = "europe-west1"
}

terraform {
  required_version = "= 1.1.6"

  backend "gcs" {
    bucket = "cmek-gke-demo-terraform-backend"
    prefix = "terraform/state"
  }

  required_providers {
    archive = {
      source  = "hashicorp/archive"
      version = "= 2.0.0"
    }

    google = {
      source  = "hashicorp/google"
      version = "= 4.6.0"
    }

    google-beta = {
      source  = "hashicorp/google-beta"
      version = "= 4.6.0"
    }
  }
}
