/**
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# Do not edit this file, it will be overwritten

resource "google_compute_network" "vpc_network" {
  project = local.project_id
  name    = "default"
}

data "google_compute_zones" "available" {
  project = local.project_id
  region  = local.project_default_region
}

resource "google_service_account" "default" {
  project      = local.project_id
  account_id   = "task-cluster-sa"
  display_name = "Service Account"
}

resource "google_container_cluster" "primary" {
  name     = "task-cluster"
  location = data.google_compute_zones.available.names[0]
  project  = local.project_id

  remove_default_node_pool = true
  initial_node_count       = 1
}

resource "google_container_node_pool" "primary_preemptible_nodes" {
  name       = "task-cluster-node-pool"
  location   = data.google_compute_zones.available.names[0]
  project    = local.project_id
  cluster    = google_container_cluster.primary.name
  node_count = 2

  node_config {
    preemptible     = true
    service_account = google_service_account.default.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    machine_type = "n1-standard-2"
    image_type   = "COS"
    disk_size_gb = 50
  }
}
