/**
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# Do not edit this file, it will be overwritten

resource "google_compute_network" "vpc_network" {
  project = local.project_id
  name    = "default"
}

data "google_compute_zones" "available" {
  project = local.project_id
  region  = local.project_default_region
}

resource "google_service_account" "default" {
  project      = local.project_id
  account_id   = "task-cluster-sa"
  display_name = "Service Account"
}

# Compute Service account for CloudDeploy to deploy the artifacts in GKE
resource "google_project_iam_member" "compute_sa_logs_writer" {
  project = local.project_id
  role    = "roles/logging.logWriter"
  member  = "serviceAccount:${google_service_account.default.email}"
}

resource "google_project_iam_member" "compute_sa_artifactregistry_reader" {
  project = local.project_id
  role    = "roles/artifactregistry.reader"
  member  = "serviceAccount:${google_service_account.default.email}"
}

resource "google_container_cluster" "primary" {
  name     = "task-cluster"
  location = local.project_default_region
  project  = local.project_id

  remove_default_node_pool = true
  initial_node_count       = 1

  addons_config {
    http_load_balancing {
      disabled = false
    }
  }

  node_config {
    service_account = google_service_account.default.email
    boot_disk_kms_key = google_kms_crypto_key.flaskapp-key.id
  }
}

resource "google_container_node_pool" "primary_nodes" {
  name           = "task-cluster-node-pool"
  location       = local.project_default_region
  node_locations = [data.google_compute_zones.available.names[0], data.google_compute_zones.available.names[1]]
  project        = local.project_id
  cluster        = google_container_cluster.primary.name
  node_count     = 2

  node_config {
    service_account = google_service_account.default.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    machine_type      = "n1-standard-2"
    image_type        = "COS"
    disk_size_gb      = 50
    disk_type         = "pd-standard"
    boot_disk_kms_key = google_kms_crypto_key.flaskapp-key.id
  }
}

resource "google_artifact_registry_repository" "repo" {
  provider      = google-beta
  project       = local.project_id
  location      = local.project_default_region
  repository_id = "flask-api"
  description   = "Docker repository"
  format        = "DOCKER"
}

resource "google_compute_global_address" "api-static-address" {
  name    = "flaskapi-static-address"
  project = local.project_id
}