#!/bin/bash

export PROJECTID="cmek-gke-demo" # ProjectID we will use for the creation
export PROJECT_NUMBER="234687475375" # ProjectID we will use for the creation
export GCP_ORGID="693611386598"              # Id of your organisation
export BILLING_ACCOUNT_ID="012A11-72C990-37B541"      # to be used by the imde project
export LOCATION="eu"                           # We recomend to use EU or US
export REGION="europe-west1"
export ZONE="europe-west1-b"
export CLUSTER_NAME="task-cluster"

gcloud config set project ${PROJECTID}
gcloud config set compute/zone ${ZONE}

gsutil mb -l ${REGION} gs://${PROJECTID}-terraform-backend

cat <<EOF > $PWD/config.tf
/**
 * Copyright 2021 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# Do not edit this file, it will be overwritten
locals {
  project_id             = "${PROJECTID}"
  project_number         = ${PROJECT_NUMBER}
  project_default_region = "${REGION}"
}

terraform {
  required_version = "= 1.1.6"

  backend "gcs" {
    bucket = "${PROJECTID}-terraform-backend"
    prefix = "terraform/state"
  }

  required_providers {
    archive = {
      source  = "hashicorp/archive"
      version = "= 2.0.0"
    }

    google = {
      source  = "hashicorp/google"
      version = "= 4.6.0"
    }

    google-beta = {
      source  = "hashicorp/google-beta"
      version = "= 4.6.0"
    }
  }
}
EOF

eval "terraform init -reconfigure"
eval "terraform apply -auto-approve"


# GKE setup
gcloud container clusters get-credentials task-cluster --region europe-west1
gcloud components install kubectl
kubectl apply -f k8s/postgres-secrets.yaml 
kubectl apply -f k8s/postgres-pv.yaml 
kubectl apply -f k8s/postgres-deployment.yaml 
kubectl apply -f k8s/postgres-service.yaml
gcloud builds submit --config=cloudbuild.yaml

echo 'Is the database created?'
echo '[0]: YES'
echo '[1]: NO'

read -p 'DB Created?: ' db

case $db in

    0)
        kubectl apply -f k8s/flaskapp-deployment.yaml 
        ;;

    1)
        echo "Refer to README to create the DB"
        ;;

    *)
        echo "Unknown choice. Type 0 or 1"
        exit 0
        ;;
esac


